import { SPEAKER_TYPE, FEE } from './App';

export const SEED_DATA = [
  {
    id: "sp-1",
    type: SPEAKER_TYPE.MEMBER,
    name: "Aisha Tan",
    chapter: "EO Singapore",
    city: "Singapore",
    country: "Singapore",
    topics: ["Scaling Up", "AI Literacy", "Marketing", "Web3", "Future of Work"],
    formats: ["Talk", "Workshop", "Virtual"],
    languages: ["English"],
    fee: FEE.NO_FEE,
    rating: { avg: 4.8, count: 17 },
    lastVerified: "2025-08-20",
    bio: "Operator-turned-coach who scaled a B2B SaaS to APAC coverage. Aisha provides actionable frameworks for sustainable growth and is a sought-after keynote speaker on AI literacy for executives.",
    links: { linkedin: "https://linkedin.com", website: "https://website.com", video: "https://video.com" },
    contact: { email: "aisha.tan@eo.mock", phone: "+65 1234 5678" },
    reviews: [
      { by: "R. Lim (EO SG)", date: "2025-07-12", rating: 5, comment: "Actionable frameworks; engaging." },
      { by: "J. Doe (EO KL)", date: "2025-06-20", rating: 4, comment: "Great content, but could be more interactive." },
    ],
    insights: [
      { title: "Pricing Experiments", date: "2025-06-18", link: "#", summary: "Low-risk test ladder." },
    ],
    eventHistory: [
        { chapter: "EO Singapore", date: "2025-07-10" },
        { chapter: "EO Kuala Lumpur", date: "2025-06-18" },
    ],
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286de2?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-11",
    type: SPEAKER_TYPE.MEMBER,
    name: "Ben Carter",
    chapter: "EO Melbourne",
    city: "Melbourne",
    country: "Australia",
    topics: ["Venture Capital", "Angel Investing", "Pitch Coaching"],
    formats: ["Panel", "Fireside Chat", "Virtual"],
    languages: ["English"],
    fee: FEE.PAID,
    rating: { avg: 4.9, count: 21 },
    lastVerified: "2025-08-30",
    bio: "A seasoned venture capitalist and angel investor, Ben has funded over 50 startups. He now dedicates his time to coaching founders on crafting the perfect pitch to secure funding.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "ben.carter@eo.mock", phone: "+61 412 345 678" },
    rate: { currency: "AUD", min: 3000, max: 5000, unit: "per session", notes: "Special rate for EO chapters.", lastUpdated: "2025-08-15", discountMulti: 25 },
    reviews: [{ by: "A. Lee (EO Melbourne)", date: "2025-08-01", rating: 5, comment: "Ben's pitch workshop was a game-changer for our members." }],
    insights: [],
    eventHistory: [{ chapter: "EO Melbourne", date: "2025-07-20" }],
    photoUrl: "https://images.unsplash.com/photo-1624298357597-fd92dfbec01d?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-2",
    type: SPEAKER_TYPE.PRO,
    name: "Dr. Kenji Tanaka",
    chapter: "—",
    city: "Tokyo",
    country: "Japan",
    topics: ["Robotics", "Future of Manufacturing", "Automation"],
    formats: ["Keynote", "Panel"],
    languages: ["Japanese", "English"],
    fee: FEE.PRO_PAID,
    rating: { avg: 4.9, count: 12 },
    lastVerified: "2025-08-22",
    bio: "A leading roboticist from the University of Tokyo, Dr. Tanaka's work is at the forefront of industrial automation. He advises corporations on integrating robotics into their manufacturing processes.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "kenji.tanaka@pro.mock", phone: "+81 90-1234-5678" },
    rate: { currency: "JPY", min: 500000, max: 800000, unit: "per engagement", notes: "Discount available for multi-day events.", lastUpdated: "2025-08-01", discountMulti: 10 },
    reviews: [{ by: "M. Sato (EO Tokyo)", date: "2025-07-15", rating: 5, comment: "Mind-blowing presentation on the future." }],
    insights: [],
    eventHistory: [{ chapter: "EO Tokyo", date: "2025-07-14" }],
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-3",
    type: SPEAKER_TYPE.MEMBER,
    name: "Isabella Rossi",
    chapter: "EO Sydney",
    city: "Sydney",
    country: "Australia",
    topics: ["Sustainable Business", "Circular Economy", "B-Corps"],
    formats: ["Workshop", "Talk"],
    languages: ["English"],
    fee: FEE.EXPENSES,
    rating: { avg: 4.7, count: 9 },
    lastVerified: "2025-08-18",
    bio: "Founder of a certified B-Corp in the sustainable fashion space. Isabella is a passionate advocate for the circular economy and helps businesses adopt more ethical and sustainable practices.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "isabella.rossi@eo.mock", phone: "+61 423 456 789" },
    reviews: [{ by: "L. Chen (EO Melbourne)", date: "2025-06-25", rating: 5, comment: "Truly inspiring and practical advice." }],
    insights: [{ title: "The B-Corp Journey", date: "2025-06-01", link: "#", summary: "From idea to certification." }],
    eventHistory: [{ chapter: "EO Melbourne", date: "2025-06-24" }],
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-4",
    type: SPEAKER_TYPE.PRO,
    name: "Dr. Maya Chen",
    chapter: "—",
    city: "Taipei",
    country: "Taiwan",
    topics: ["Generative AI", "Ethics", "Risk"],
    formats: ["Talk", "Workshop"],
    languages: ["English", "Mandarin"],
    fee: FEE.PRO_PAID,
    rating: { avg: 4.5, count: 6 },
    lastVerified: "2025-08-10",
    bio: "AI researcher and policy advisor with a PhD from Stanford. Dr. Chen specializes in creating founder-ready governance toolkits that balance innovation with ethical responsibility.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "maya.chen@pro.mock", phone: "+886 912 345 678" },
    rate: { currency: "USD", min: 4000, max: 7000, unit: "per talk", notes: "Plus travel & lodging.", lastUpdated: "2025-08-05", discountMulti: 15 },
    reviews: [ { by: "D. Nguyen (EO HCMC)", date: "2025-08-01", rating: 5, comment: "Balanced governance view." } ],
    insights: [ { title: "Practical AI Risk Registers", date: "2025-07-09", link: "#", summary: "Template that sticks." } ],
    eventHistory: [],
    photoUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-5",
    type: SPEAKER_TYPE.MEMBER,
    name: "Priya Mehta",
    chapter: "EO Mumbai",
    city: "Mumbai",
    country: "India",
    topics: ["Leadership", "Storytelling"],
    formats: ["Talk", "Virtual"],
    languages: ["English", "Hindi"],
    fee: FEE.NO_FEE,
    rating: { avg: 4.9, count: 22 },
    lastVerified: "2025-08-02",
    bio: "Founder of a 500-person logistics organization, Priya teaches narrative leadership after taking her company through a period of hypergrowth and successful exit. Her stories truly resonate.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "priya.mehta@eo.mock", phone: "+91 98765 43210" },
    reviews: [ { by: "A. Rao (EO Delhi)", date: "2025-07-20", rating: 5, comment: "Stories landed." } ],
    insights: [],
    eventHistory: [],
    photoUrl: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-6",
    type: SPEAKER_TYPE.MEMBER,
    name: "David Kim",
    chapter: "EO Seoul",
    city: "Seoul",
    country: "South Korea",
    topics: ["K-Culture", "Global Branding", "Entertainment Tech"],
    formats: ["Talk", "Fireside Chat"],
    languages: ["Korean", "English"],
    fee: FEE.NO_FEE,
    rating: { avg: 4.8, count: 15 },
    lastVerified: "2025-08-25",
    bio: "Executive producer behind several globally successful K-pop groups. David shares insights on building a cultural phenomenon and leveraging technology in the entertainment industry.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "david.kim@eo.mock", phone: "+82 10-1234-5678" },
    reviews: [{ by: "S. Park (EO Seoul)", date: "2025-08-05", rating: 5, comment: "Fascinating look behind the curtain of K-pop." }],
    insights: [],
    eventHistory: [],
    photoUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-7",
    type: SPEAKER_TYPE.PRO,
    name: "Dr. Ananya Sharma",
    chapter: "—",
    city: "Bengaluru",
    country: "India",
    topics: ["FinTech", "Digital Payments", "Blockchain"],
    formats: ["Keynote", "Workshop"],
    languages: ["English", "Hindi"],
    fee: FEE.PRO_PAID,
    rating: { avg: 4.9, count: 18 },
    lastVerified: "2025-08-15",
    bio: "A leading authority on digital finance in emerging markets. Dr. Sharma founded a successful FinTech startup and now consults for central banks on digital currency adoption.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "ananya.sharma@pro.mock", phone: "+91 98765 01234" },
    rate: { currency: "INR", min: 350000, unit: "per keynote", lastUpdated: "2025-07-30", discountMulti: 20 },
    reviews: [{ by: "R. Kumar (EO Bangalore)", date: "2025-07-10", rating: 5, comment: "She made blockchain understandable and relevant." }],
    insights: [],
    eventHistory: [],
    photoUrl: "https://images.unsplash.com/photo-1552058544-f2b08422138a?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-8",
    type: SPEAKER_TYPE.MEMBER,
    name: "Liam Murphy",
    chapter: "EO New Zealand",
    city: "Auckland",
    country: "New Zealand",
    topics: ["AgriTech", "Export Strategy", "Sustainability"],
    formats: ["Talk", "Roundtable"],
    languages: ["English"],
    fee: FEE.EXPENSES,
    rating: { avg: 4.6, count: 7 },
    lastVerified: "2025-08-12",
    bio: "CEO of a multi-generational farming enterprise that transformed into a global AgriTech leader. Liam speaks on modernizing traditional industries and cracking international markets.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "liam.murphy@eo.mock", phone: "+64 21 123 4567" },
    reviews: [{ by: "S. Taylor (EO NZ)", date: "2025-06-15", rating: 4, comment: "Solid content, a bit dry on delivery." }],
    insights: [],
    eventHistory: [],
    photoUrl: "https://images.unsplash.com/photo-1566753323558-f4e0952af115?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-9",
    type: SPEAKER_TYPE.PRO,
    name: "Sofia Reyes",
    chapter: "—",
    city: "Manila",
    country: "Philippines",
    topics: ["Social Entrepreneurship", "Impact Investing", "Community Building"],
    formats: ["Workshop", "Keynote"],
    languages: ["English", "Tagalog"],
    fee: FEE.PRO_PAID,
    rating: { avg: 5.0, count: 25 },
    lastVerified: "2025-08-28",
    bio: "A globally recognized social entrepreneur who has built multiple ventures focused on poverty alleviation through technology. Sofia's workshops are highly interactive and impactful.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "sofia.reyes@pro.mock", phone: "+63 917 123 4567" },
    rate: { currency: "PHP", min: 150000, unit: "per day", lastUpdated: "2025-08-10", discountMulti: 10 },
    reviews: [{ by: "J. Santos (EO Philippines)", date: "2025-08-01", rating: 5, comment: "Absolutely life-changing. A must-book speaker." }],
    insights: [],
    eventHistory: [],
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-10",
    type: SPEAKER_TYPE.MEMBER,
    name: "Chen Wei",
    chapter: "EO Shanghai",
    city: "Shanghai",
    country: "China",
    topics: ["E-commerce", "Live Streaming", "Supply Chain"],
    formats: ["Virtual", "Talk"],
    languages: ["Mandarin"],
    fee: FEE.NO_FEE,
    rating: { avg: 4.8, count: 31 },
    lastVerified: "2025-08-20",
    bio: "Built one of China's largest live-streaming commerce platforms. Chen Wei shares tactical advice on building massive online audiences and optimizing complex supply chains for speed.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "chen.wei@eo.mock", phone: "+86 138 1234 5678" },
    reviews: [{ by: "L. Zhang (EO Shanghai)", date: "2025-07-22", rating: 5, comment: "Incredibly tactical and relevant for today's market." }],
    insights: [],
    eventHistory: [],
    photoUrl: "https://images.unsplash.com/photo-1590086782792-42dd2350160d?q=80&w=200&h=200&auto=format&fit=crop",
  },
];


