import { SPEAKER_TYPE, FEE, Speaker } from './types';

// The SEED_DATA is now explicitly typed as an array of Speaker
export const SEED_DATA: Speaker[] = [
  {
    id: "sp-1",
    type: SPEAKER_TYPE.MEMBER,
    name: "Aisha Tan",
    chapter: "EO Singapore",
    city: "Singapore",
    country: "Singapore",
    topics: ["Scaling Up", "AI Literacy", "Marketing", "Web3", "Future of Work"],
    formats: ["Talk", "Workshop", "Virtual"],
    languages: ["English"],
    fee: FEE.NO_FEE,
    rating: { avg: 4.8, count: 17 },
    lastVerified: "2025-08-20",
    bio: "Operator-turned-coach who scaled a B2B SaaS to APAC coverage. Aisha provides actionable frameworks for sustainable growth and is a sought-after keynote speaker on AI literacy for executives.",
    links: { linkedin: "https://linkedin.com", website: "https://website.com", video: "https://video.com" },
    contact: { email: "aisha.tan@eo.mock", phone: "+65 1234 5678" },
    reviews: [
      { by: "R. Lim (EO SG)", date: "2025-07-12", rating: 5, comment: "Actionable frameworks; engaging." },
      { by: "J. Doe (EO KL)", date: "2025-06-20", rating: 4, comment: "Great content, but could be more interactive." },
    ],
    insights: [
      { title: "Pricing Experiments", date: "2025-06-18", link: "#", summary: "Low-risk test ladder." },
    ],
    eventHistory: [
        { chapter: "EO Singapore", date: "2025-07-10" },
        { chapter: "EO Kuala Lumpur", date: "2025-06-18" },
    ],
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286de2?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-11",
    type: SPEAKER_TYPE.MEMBER,
    name: "Ben Carter",
    chapter: "EO Melbourne",
    city: "Melbourne",
    country: "Australia",
    topics: ["Venture Capital", "Angel Investing", "Pitch Coaching"],
    formats: ["Panel", "Fireside Chat", "Virtual"],
    languages: ["English"],
    fee: FEE.PAID,
    rating: { avg: 4.9, count: 21 },
    lastVerified: "2025-08-30",
    bio: "A seasoned venture capitalist and angel investor, Ben has funded over 50 startups. He now dedicates his time to coaching founders on crafting the perfect pitch to secure funding.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "ben.carter@eo.mock", phone: "+61 412 345 678" },
    rate: { currency: "AUD", min: 3000, max: 5000, unit: "per session", notes: "Special rate for EO chapters.", lastUpdated: "2025-08-15", discountMulti: 25 },
    reviews: [{ by: "A. Lee (EO Melbourne)", date: "2025-08-01", rating: 5, comment: "Ben's pitch workshop was a game-changer for our members." }],
    insights: [],
    eventHistory: [{ chapter: "EO Melbourne", date: "2025-07-20" }],
    photoUrl: "https://images.unsplash.com/photo-1624298357597-fd92dfbec01d?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-2",
    type: SPEAKER_TYPE.PRO,
    name: "Dr. Kenji Tanaka",
    chapter: "—",
    city: "Tokyo",
    country: "Japan",
    topics: ["Robotics", "Future of Manufacturing", "Automation"],
    formats: ["Keynote", "Panel"],
    languages: ["Japanese", "English"],
    fee: FEE.PRO_PAID,
    rating: { avg: 4.9, count: 12 },
    lastVerified: "2025-08-22",
    bio: "A leading roboticist from the University of Tokyo, Dr. Tanaka's work is at the forefront of industrial automation. He advises corporations on integrating robotics into their manufacturing processes.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "kenji.tanaka@pro.mock", phone: "+81 90-1234-5678" },
    rate: { currency: "JPY", min: 500000, max: 800000, unit: "per engagement", notes: "Discount available for multi-day events.", lastUpdated: "2025-08-01", discountMulti: 10 },
    reviews: [{ by: "M. Sato (EO Tokyo)", date: "2025-07-15", rating: 5, comment: "Mind-blowing presentation on the future." }],
    insights: [],
    eventHistory: [{ chapter: "EO Tokyo", date: "2025-07-14" }],
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-3",
    type: SPEAKER_TYPE.MEMBER,
    name: "Isabella Rossi",
    chapter: "EO Sydney",
    city: "Sydney",
    country: "Australia",
    topics: ["Sustainable Business", "Circular Economy", "B-Corps"],
    formats: ["Workshop", "Talk"],
    languages: ["English"],
    fee: FEE.EXPENSES,
    rating: { avg: 4.7, count: 9 },
    lastVerified: "2025-08-18",
    bio: "Founder of a certified B-Corp in the sustainable fashion space. Isabella is a passionate advocate for the circular economy and helps businesses adopt more ethical and sustainable practices.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "isabella.rossi@eo.mock", phone: "+61 423 456 789" },
    reviews: [{ by: "L. Chen (EO Melbourne)", date: "2025-06-25", rating: 5, comment: "Truly inspiring and practical advice." }],
    insights: [{ title: "The B-Corp Journey", date: "2025-06-01", link: "#", summary: "From idea to certification." }],
    eventHistory: [{ chapter: "EO Melbourne", date: "2025-06-24" }],
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-4",
    type: SPEAKER_TYPE.PRO,
    name: "Raj Patel",
    chapter: "—",
    city: "Mumbai",
    country: "India",
    topics: ["Fintech", "Blockchain", "Digital Payments"],
    formats: ["Keynote", "Panel", "Virtual"],
    languages: ["English", "Hindi"],
    fee: FEE.PRO_PAID,
    rating: { avg: 4.9, count: 15 },
    lastVerified: "2025-08-25",
    bio: "A pioneer in the Indian fintech space, Raj has built and sold two successful startups. He offers deep insights into the future of finance and the impact of blockchain technology.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "raj.patel@pro.mock", phone: "+91 98765 43210" },
    rate: { currency: "INR", min: 200000, max: 350000, unit: "per engagement", notes: "", lastUpdated: "2025-08-10" },
    reviews: [{ by: "S. Gupta (EO Mumbai)", date: "2025-07-20", rating: 5, comment: "Raj's session on blockchain was eye-opening." }],
    insights: [],
    eventHistory: [{ chapter: "EO Mumbai", date: "2025-07-19" }],
    photoUrl: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-5",
    type: SPEAKER_TYPE.MEMBER,
    name: "Chloe Chen",
    chapter: "EO Hong Kong",
    city: "Hong Kong",
    country: "China",
    topics: ["E-commerce", "Cross-Border Trade", "Supply Chain"],
    formats: ["Talk", "Workshop"],
    languages: ["English", "Cantonese", "Mandarin"],
    fee: FEE.NO_FEE,
    rating: { avg: 4.8, count: 11 },
    lastVerified: "2025-08-28",
    bio: "Chloe runs a successful e-commerce business that ships to over 50 countries. She shares her expertise on navigating the complexities of cross-border trade and optimizing supply chains.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "chloe.chen@eo.mock", phone: "+852 1234 5678" },
    reviews: [{ by: "T. Lee (EO Hong Kong)", date: "2025-08-05", rating: 5, comment: "Chloe's workshop was incredibly practical and helpful." }],
    insights: [],
    eventHistory: [{ chapter: "EO Hong Kong", date: "2025-08-04" }],
    photoUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-6",
    type: SPEAKER_TYPE.PRO,
    name: "Dr. Emily Carter",
    chapter: "—",
    city: "Auckland",
    country: "New Zealand",
    topics: ["Mental Health", "Wellbeing", "Resilience"],
    formats: ["Keynote", "Workshop", "Virtual"],
    languages: ["English"],
    fee: FEE.PRO_PAID,
    rating: { avg: 5.0, count: 25 },
    lastVerified: "2025-09-01",
    bio: "A clinical psychologist and author, Dr. Carter specializes in workplace mental health and resilience. Her engaging workshops provide practical tools for managing stress and improving wellbeing.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "emily.carter@pro.mock", phone: "+64 21 123 4567" },
    rate: { currency: "NZD", min: 4000, max: 6000, unit: "per session", notes: "Travel expenses not included.", lastUpdated: "2025-08-20" },
    reviews: [{ by: "J. Wilson (EO Auckland)", date: "2025-08-15", rating: 5, comment: "Emily's session was the highlight of our event. Incredibly impactful." }],
    insights: [],
    eventHistory: [{ chapter: "EO Auckland", date: "2025-08-14" }],
    photoUrl: "https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=200&h=200&auto=format&fit=crop",
  }
];


