import { SPEAKER_TYPE, FEE, Speaker } from './types';

// The SEED_DATA is now explicitly typed as an array of Speaker
export const SEED_DATA: Speaker[] = [
  {
    id: "sp-1",
    type: SPEAKER_TYPE.MEMBER,
    name: "Aisha Tan",
    chapter: "EO Singapore",
    city: "Singapore",
    country: "Singapore",
    topics: ["Scaling Up", "AI Literacy", "Marketing", "Web3", "Future of Work"],
    formats: ["Talk", "Workshop", "Virtual"],
    languages: ["English"],
    fee: FEE.NO_FEE,
    rating: { avg: 4.8, count: 17 },
    lastVerified: "2025-08-20",
    bio: "Operator-turned-coach who scaled a B2B SaaS to APAC coverage. Aisha provides actionable frameworks for sustainable growth and is a sought-after keynote speaker on AI literacy for executives.",
    links: { linkedin: "https://linkedin.com", website: "https://website.com", video: "https://video.com" },
    contact: { email: "aisha.tan@eo.mock", phone: "+65 1234 5678" },
    reviews: [
      { by: "R. Lim (EO SG)", date: "2025-07-12", rating: 5, comment: "Actionable frameworks; engaging." },
      { by: "J. Doe (EO KL)", date: "2025-06-20", rating: 4, comment: "Great content, but could be more interactive." },
    ],
    insights: [
      { title: "Pricing Experiments", date: "2025-06-18", link: "#", summary: "Low-risk test ladder." },
    ],
    eventHistory: [
        { chapter: "EO Singapore", date: "2025-07-10" },
        { chapter: "EO Kuala Lumpur", date: "2025-06-18" },
    ],
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286de2?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-11",
    type: SPEAKER_TYPE.MEMBER,
    name: "Ben Carter",
    chapter: "EO Melbourne",
    city: "Melbourne",
    country: "Australia",
    topics: ["Venture Capital", "Angel Investing", "Pitch Coaching"],
    formats: ["Panel", "Fireside Chat", "Virtual"],
    languages: ["English"],
    fee: FEE.PAID,
    rating: { avg: 4.9, count: 21 },
    lastVerified: "2025-08-30",
    bio: "A seasoned venture capitalist and angel investor, Ben has funded over 50 startups. He now dedicates his time to coaching founders on crafting the perfect pitch to secure funding.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "ben.carter@eo.mock", phone: "+61 412 345 678" },
    rate: { currency: "AUD", min: 3000, max: 5000, unit: "per session", notes: "Special rate for EO chapters.", lastUpdated: "2025-08-15", discountMulti: 25 },
    reviews: [{ by: "A. Lee (EO Melbourne)", date: "2025-08-01", rating: 5, comment: "Ben's pitch workshop was a game-changer for our members." }],
    insights: [],
    eventHistory: [{ chapter: "EO Melbourne", date: "2025-07-20" }],
    photoUrl: "https://images.unsplash.com/photo-1624298357597-fd92dfbec01d?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-2",
    type: SPEAKER_TYPE.PRO,
    name: "Dr. Kenji Tanaka",
    chapter: "—",
    city: "Tokyo",
    country: "Japan",
    topics: ["Robotics", "Future of Manufacturing", "Automation"],
    formats: ["Keynote", "Panel"],
    languages: ["Japanese", "English"],
    fee: FEE.PRO_PAID,
    rating: { avg: 4.9, count: 12 },
    lastVerified: "2025-08-22",
    bio: "A leading roboticist from the University of Tokyo, Dr. Tanaka's work is at the forefront of industrial automation. He advises corporations on integrating robotics into their manufacturing processes.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "kenji.tanaka@pro.mock", phone: "+81 90-1234-5678" },
    rate: { currency: "JPY", min: 500000, max: 800000, unit: "per engagement", notes: "Discount available for multi-day events.", lastUpdated: "2025-08-01", discountMulti: 10 },
    reviews: [{ by: "M. Sato (EO Tokyo)", date: "2025-07-15", rating: 5, comment: "Mind-blowing presentation on the future." }],
    insights: [],
    eventHistory: [{ chapter: "EO Tokyo", date: "2025-07-14" }],
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&h=200&auto=format&fit=crop",
  },
  {
    id: "sp-3",
    type: SPEAKER_TYPE.MEMBER,
    name: "Isabella Rossi",
    chapter: "EO Sydney",
    city: "Sydney",
    country: "Australia",
    topics: ["Sustainable Business", "Circular Economy", "B-Corps"],
    formats: ["Workshop", "Talk"],
    languages: ["English"],
    fee: FEE.EXPENSES,
    rating: { avg: 4.7, count: 9 },
    lastVerified: "2025-08-18",
    bio: "Founder of a certified B-Corp in the sustainable fashion space. Isabella is a passionate advocate for the circular economy and helps businesses adopt more ethical and sustainable practices.",
    links: { linkedin: "#", website: "#", video: "#" },
    contact: { email: "isabella.rossi@eo.mock", phone: "+61 423 456 789" },
    reviews: [{ by: "L. Chen (EO Melbourne)", date: "2025-06-25", rating: 5, comment: "Truly inspiring and practical advice." }],
    insights: [{ title: "The B-Corp Journey", date: "2025-06-01", link: "#", summary: "From idea to certification." }],
    eventHistory: [{ chapter: "EO Melbourne", date: "2025-06-24" }],
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&h=200&auto=format&fit=crop",
  },
  // ...The rest of the speaker profiles from the previous version...
];


